name: frontend
version: 0.0.0.1
github: "ibizaman/hs-reflex-tvdb/frontend"
license: BSD3
author: "Pierre Penninckx"
maintainer: "Pierre Penninckx"
copyright: "2021 Pierre Penninckx"

description: Please see the README on GitHub at <https://ibizaman/hs-reflex-tvdb/frontend>

dependencies:
    - base >= 4.7 && < 5
    - clay >= 0.13.0 && < 1
    - common
    - containers >= 0.6 && < 0.7
    - text >= 1.2 && < 1.3
    - reflex >= 0.8 && < 0.9
    - reflex-dom >= 0.6 && < 0.7
    - servant >= 0.16.2 && < 1
    - servant-server >= 0.16.2 && < 1
    - servant-reflex >= 0.3.6 && < 0.5

default-extensions:
    - OverloadedStrings

library:
    source-dirs: src
    dependencies: {}

executables:
    frontend-nocss:
        main: Main.hs
        source-dirs: app/NoCss
        dependencies:
            - frontend
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

    frontend-externcss:
        main: Main.hs
        source-dirs: app/ExternalCss
        dependencies:
            - frontend
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

    frontend-generatecss:
        main: Main.hs
        source-dirs: app/GenerateCss
        dependencies:
            - frontend
            - cmdargs >= 0.10 && <1
            - directory >= 1.3 && <2
            - filepath >= 1.3 && <2
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-record-updates
    - -fwarn-incomplete-uni-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    - -fwarn-overlapping-patterns
    - -fwarn-tabs
    - -fwarn-unused-imports
